return function (e)
	local scene = getEntityScene(e)
	love.graphics.setColor(properties.color.player)
	local x, y, w, h = scene.bump:getRect(e)
	local lineWidth = love.graphics.getLineWidth()
	love.graphics.setLineWidth(5)
	love.graphics.push()
	love.graphics.translate(x + w / 2, y + h / 2)
	love.graphics.scale(1.2)
	love.graphics.translate(-w / 6, 0)
	-- love.graphics.scale(1 - t * 0.6)
	-- love.graphics.rectangle('fill', 0 - w / 2, 0 - h / 2, w, h, 4, nil, 50)
	love.graphics.circle('line', 0, 0, w / 2 / 4, 50)
	love.graphics.line(w / 2 / 4, 0, w / 2 / 4 * 4, 0)
	love.graphics.rectangle('fill', w / 2 / 4 * 3, 0, w / 2 / 4 * 1, w / 8, w / 32)
	love.graphics.pop()
	love.graphics.setLineWidth(lineWidth)
end